# Generated by Django 3.2 on 2021-05-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='brand',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AddField(
            model_name='index',
            name='category',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='index',
            name='img',
            field=models.ImageField(default='https://cdn.pixabay.com/photo/2017/07/02/19/24/dumbbells-2465478_960_720.jpg', upload_to='images'),
        ),
        migrations.AddField(
            model_name='index',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='index',
            name='pub_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='description',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='index',
            name='name',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
